### ISSUE TITLE
input selector to tv does not work

### ISSUE THREAD

**Issue by domi-a** [estbeetoo/node-red-contrib-eiscp#11]
great module. love it.

only thing i cant get to work: set the input to the "TV" aka hdmi with ARC.
i can turn it on and off and change volume and other stuff.
but with payload: "input-selector=Video1" nothing is happening.
i can control my pioneer vsx-933 from the app, wich means it is possible over eiscp to switch to TV input.
i read the commands at https://raw.githubusercontent.com/tillbaks/node-eiscp/master/eiscp-commands.json wich showed me it should be input-selector=Video1
i researched and tried for a couple of hours an only this thing does not work.

am i doing something wrong?

**Comment by thomasvjohansen** [comment]
I have a Onkyo TX-NR636 and I use source "TV/CD" for tv-sound.

In node-red I use the "CD" to select this source :
`msg.payload = "input-selector=CD";
return msg;`

**Comment by domi-a** [comment]
thank you for replying. i totally forgot this gh-issue.

menwhile it is working with "input-selector=Video1" that exaclty thing that did nor work in first place.
i'm not sure if the module version is newer or it was something else with my avr.

i'm guessing it was the avr. when sending lot of eiscp commands there seems to be a delay of many seconds to be involved.
this especally happens when switching to tv.
