### ISSUE TITLE
Send raw commands to receiver?

### ISSUE THREAD

**Issue by crxporter** [estbeetoo/node-red-contrib-eiscp#5]
This node is working for MOST of the functionality I'm looking for. Great work so far! 

I am looking for a way to send raw commands to my receiver. The current source of the EISCP in this node looks to be over 3 years old. I have a 2018 receiver - it would be great to send raw commands to the receiver.

For example instead of sending `system-power=on` I would like to send `PWR01`. This may already work but I can't find any documentation on how to send it... Any help would be appreciated!

**Comment by djiwondee** [comment]
@crxporter Try this [approach](https://github.com/NRCHKB/node-red-contrib-homekit-bridged/issues/94#issuecomment-502153247) ;-)

**Comment by onokje** [comment]
I created a PR for this, that makes this really easy.
https://github.com/estbeetoo/node-red-contrib-eiscp/pull/6
I use it at home, works like a charm. (I have a TX-NR535)

**Comment by crxporter** [comment]
Awesome! I think I have things working how I need but this opens up ALL commands, right? Bypasses the json list of “valid commands” and sends any raw command?

I recently upgraded to an tx-rz630 which has many commands not included in the years old list this plugin uses. It does work great with what it knows though...

**Comment by crxporter** [comment]
#6 fixes my issue. Thanks.

**Comment by onokje** [comment]
> this opens up ALL commands, right? Bypasses the json list of “valid commands” and sends any raw command?

Exactly.
